### ISSUE TITLE
incorrect peer dependency

### ISSUE THREAD

**Issue by ceghap** [Idered/eslint-plugin-tailwind#11]
```warning " > eslint-plugin-tailwind@0.2.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".```

I am using eslint^7.0.0

**Comment by yhafez** [comment]
Also having this issue. Just added the fixed the peer dependency and sent in a PR

**Comment by ryck** [comment]
Can we have a new release then to reflect this changes?

**Comment by Idered** [comment]
Released in 0.2.1
